# Generated by Django 5.0.7 on 2024-07-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalBoss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('edad_nominal', models.IntegerField()),
            ],
        ),
    ]
