# Generated by Django 5.0.7 on 2024-07-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalBoss', '0002_transformeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeddata',
            name='raw_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finalBoss.rawdata'),
        ),
    ]
