# Generated by Django 5.0.7 on 2024-07-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalBoss', '0003_transformeddata_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformeddata',
            name='raw_data',
        ),
    ]
